name: mocpy-dev

channels:
- defaults
- conda-forge

dependencies:
- astropy
- astropy-healpix
- astroquery
- jupyter
- matplotlib
- nbconvert
- nbformat
- numpy
- pytest
- pytest-cov
- requests
- six
- sphinx
- pip:
  - numpydoc
